name: Generate offline dataset

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build-release-bundle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'  # Not needed with a .ruby-version file
        bundler-cache: true  # runs 'bundle install' and caches installed gems automatically
    # Generate .json files under ./api/
    - run: bundle exec ruby ./_plugins/create-json-files.rb
    # Generate a tar bundle from those files.
    - run: (cd ./api/ && tar --mode='a+rw' -czvf ../dataset.tar.gz *.json)
    # DEBUG: Confirm the bundle worked by listing the files it contains.
    - run: tar -tzvf dataset.tar.gz
    # Publish the release
    - uses: ncipollo/release-action@v1
      with:
        name: "latest"
        artifacts: "dataset.tar.gz"
        allowUpdates: true
        artifactErrorsFailBuild: true
        makeLatest: true
